# Лабораторная работа №1

## Выполнил студент группы БФИ1902 Клишин М.С.

### Цель лабораторной работы
Познакомиться с функционалом Jupyter Notebook. Узнать и реализовать разные виды сортировок

### Задание на лабораторную работу

### Задание №1:
1. Создать Jupyter Notebook со следующим наименованием: Lab1_Группа_ФИО
2. Написать и запустить программу "Hello World" в новой ячейке

### Задание №2:
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
матрицы, а min_lim и max_lim - минимальное и максимальное значение для
генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
значения:
m = 50
n = 50
min_limit = -250
max_limit = 1000 + (номер своего варианта)

### Задание №3:
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.
Сортировки:
1. Выбором
2. Вставкой
3. Обмена
4. Шелла
5. Турнирная
6. Быстрая
7. Пирамидальная

### Задание №4:
Создать публичный репозиторий на github, и запушить выполненное задание в
.ipynb формате.

### Ход выполнение лабораторной работы

### Задание №1

In [1]:
print("Hello World!")

Hello World!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры m, n, min_limit, max_limit, где m и n указывают размер
матрицы, а min_lim и max_lim - минимальное и максимальное значение для
генерируемого числа . По умолчанию при отсутствии параметров принимать следующие
значения:
m = 50
n = 50
min_limit = -250
max_limit = 1000 + (номер своего варианта)

In [2]:
%%time
from random import randint
import numpy as np

n=50
m=50
min=-250
max=1005

a=[[randint(min,max) for j in range(m)] for i in range(n)]
an= np.asarray(a)
print(an)


[[ 984   66  594 ...  973  896  590]
 [ 617  364   82 ...  178 -169  728]
 [ 403  -29 -107 ...  -75  517  434]
 ...
 [ 320  676  135 ... -225  496 -104]
 [ 242  325  990 ...  426  817  791]
 [ 728  567  976 ... -210  554   42]]
Wall time: 148 ms


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.
Методы:
Выбором Вставкой Обменом Шелла Турнирная Быстрая сортировка Пирамидальная

### Сортировка Выбором

In [3]:
%%time
import numpy as np
def sel(arr):
    for i in range(len(arr)):
        low=i
        for j in range(i+1, len(arr)):
            if arr[j]< arr[low]:
                low=j
                arr[i],arr[low]= arr[low], arr[i]
k=0
while k<n:
    sel(a[k])
    k=k+1
an=np.asarray(a)
print(an)

[[  20 -240  -31 ...  590   66  984]
 [-199 -197 -111 ...  823  953  958]
 [-143 -220   38 ...  988  988 1001]
 ...
 [-225 -216 -114 ...  676  988  997]
 [-197 -211   22 ...  325  990 1000]
 [-198 -210 -237 ...  728  976  986]]
Wall time: 11.2 ms


### Сортировка вставкой

In [4]:
%%time
import numpy as np

def insert(arr):
    for i in range(1,len(arr)):
        ins=arr[i]
        j=i-1
    while j >=0 and arr[i]>ins:
        arr[j+1]=arr[j]
        j=j-1
        arr[j+1]=ins
k=0
while k<n:
    insert(a[k])
    k=k+1
an=np.asarray(a)
print(an)

[[  20 -240  -31 ...  590   66  984]
 [-199 -197 -111 ...  823  953  958]
 [-143 -220   38 ...  988  988 1001]
 ...
 [-225 -216 -114 ...  676  988  997]
 [-197 -211   22 ...  325  990 1000]
 [-198 -210 -237 ...  728  976  986]]
Wall time: 750 µs


### Сортировка методом пузырька

In [5]:
%%time
import numpy as np
def obmen(arr):
    obm = True
    while obm:
        obm = False
        for i in range(len(arr)-1):
            if arr[i]> arr[i+1]:
                arr[i], arr[i+1] = arr[i+1], arr[i]
                obm= True
k=0
while k<n:
    obmen(a[k])
    k=k+1
an= np.asarray(a)
print(an)

[[-240 -209 -125 ...  941  973  984]
 [-209 -199 -197 ...  948  953  958]
 [-228 -220 -201 ...  988  988 1001]
 ...
 [-225 -216 -216 ...  984  988  997]
 [-246 -211 -197 ...  987  990 1000]
 [-237 -210 -198 ...  957  976  986]]
Wall time: 12 ms


### Сортировка Шелла

In [6]:
%%time
import numpy as np

def shell(arr):
    inc = len(arr)//2
    while inc:
        for i, el in enumerate(arr):
            while i>=inc and arr[i-inc]> el:
                arr[i]= arr[i-inc]
                i= i - inc
                arr[i]=el
                inc=int(inc//2)
            return arr
k=0
while k<n:
    shell(a[k])
    k=k+1
an=np.asarray(a)
print(an)

[[-240 -209 -125 ...  941  973  984]
 [-209 -199 -197 ...  948  953  958]
 [-228 -220 -201 ...  988  988 1001]
 ...
 [-225 -216 -216 ...  984  988  997]
 [-246 -211 -197 ...  987  990 1000]
 [-237 -210 -198 ...  957  976  986]]
Wall time: 749 µs


### Быстрая сортировка 

In [8]:
%%time
import numpy as np
def quicksort(nums):
    if len(nums) <= 1:
        return nums
    else:
        q = random.choice(nums)
    s_nums = []
    m_nums = []
    e_nums = []
    for n in nums:
        if n < q:
            s_nums.append(n)
            elif n > q:
                m_nums.append(n) else:
                        e_nums.append(n)
                        return quicksort(s_nums) + e_nums + quicksort(m_nums)
k=0
while k<n:
    heapsort(a[k])
    k=k+1
an=np.asarray(a)
print(an)

IndentationError: unexpected indent (<unknown>, line 10)

### Пирамидальная сортировка

In [ ]:
%%time
import numpy as np
def heapsort(alist):
build_max_heap(alist)
for i in range(len(alist) - 1, 0, -1):
alist[0], alist[i] = alist[i], alist[0]
max_heapify(alist, index=0, size=i)

def parent(i):
return (i - 1)//2

def left(i):
return 2*i + 1

def right(i):
return 2*i + 2

def build_max_heap(alist):
length = len(alist)
start = parent(length - 1)
while start >= 0:
max_heapify(alist, index=start, size=length)
start = start - 1

def max_heapify(alist, index, size):
l = left(index)
r = right(index)
if (l < size and alist[l] > alist[index]):
largest = l
else:
largest = index
if (r < size and alist[r] > alist[largest]):
largest = r
if (largest != index):
alist[largest], alist[index] = alist[index], alist[largest]
max_heapify(alist, largest, size)
k=0
while k<n:
heapsort(a[k])
k=k+1
an=np.asarray(a)
print(an)

### Турнирная сортировка

In [ ]:
%%time
import numpy as np

def tournamentSort(arr):
tree = [None] * 2 * (len(arr) + len(arr) % 2)
index = len(tree) - len(arr) - len(arr) % 2

for i, v in enumerate(arr):
tree[index + i] = (i, v)

for j in range(len(arr)):
n = len(arr)
index = len(tree) - len(arr) - len(arr) % 2
while index > -1:
n = (n + 1) // 2
for i in range(n):
i = max(index + i * 2, 1)
if tree[i] is not None and tree[i + 1] is not None:
if tree[i] < tree[i + 1]:
tree[i // 2] = tree[i]
else:
tree[i // 2] = tree[i + 1]
else:
tree[i // 2] = tree[i] if tree[i] is not None else tree[i + 1]
index -= n

index, x = tree[0]
arr[j] = x
tree[len(tree) - len(arr) - len(arr) % 2 + index] = None

k=0
while k<n:
tournamentSort(a[k])
k=k+1
an=np.asarray(a)
print(an)

### Вывод
В процессе выполнения данной лабораторной работы мы познакомились с базовым функционалом Jupyter Notebook и реализовали разные виды сортировок